version: 2.1

# Aliases to reuse
_defaults: &defaults
  docker:
    # CircleCI maintains a library of pre-built images
    # documented at https://circleci.com/docs/2.0/circleci-images/
    - image: cimg/python:3.11
  working_directory: ~/repo

commands:
  check-skip:
    steps:
      - run:
          name: Check-skip
          command: |
            if [ ! -d "scipy" ]; then
              echo "Build was not run due to skip, exiting job ${CIRCLE_JOB} for PR ${CIRCLE_PULL_REQUEST}."
              circleci-agent step halt;
            fi

            export git_log=$(git log --max-count=1 --pretty=format:"%B" | tr "\n" " ")
            echo "Got commit message:"
            echo "${git_log}"
            if [[ -v CIRCLE_PULL_REQUEST ]] && ([[ "$git_log" == *"[skip circle]"* ]] || [[ "$git_log" == *"[circle skip]"* ]] || [[ "$git_log" == *"[lint only]"* ]]); then
              echo "Skip detected, exiting job ${CIRCLE_JOB} for PR ${CIRCLE_PULL_REQUEST}."
              circleci-agent step halt;
            fi

  apt-install:
    steps:
      - run:
          name: Install apt packages
          command: |
            sudo apt-get update
            sudo apt-get install libopenblas-dev gfortran libgmp-dev libmpfr-dev ccache

  merge:
    steps:
      - run:
          name: merge with upstream
          command: |
            echo $(git log -1 --pretty=%B) | tee gitlog.txt
            echo ${CI_PULL_REQUEST//*pull\//} | tee merge.txt
            if [[ $(cat merge.txt) != "" ]]; then
              echo "Merging $(cat merge.txt)";
              git remote add upstream https://github.com/scipy/scipy.git;
              git pull --ff-only upstream "refs/pull/$(cat merge.txt)/merge";
              git fetch upstream main;
            fi

jobs:
# Build SciPy from source
  build_scipy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - checkout
      - check-skip
      - merge

      - apt-install

      - run:
          name: update submodules
          command: |
            git submodule init
            git submodule update

      - run:
          name: setup Python venv
          command: |
            pip install numpy cython pybind11 pythran ninja meson
            pip install -r requirements/doc.txt
            pip install mpmath gmpy2 "asv>=0.6.0" click rich-click doit pydevtool pooch threadpoolctl scipy

      - run:
          name: build docs
          no_output_timeout: 25m
          command: |
            export PYTHONPATH=$PWD/build-install/lib/python3.11/site-packages
            python dev.py --no-build doc 2>&1 | tee sphinx_log.txt


workflows:
  version: 2
  default:
    jobs:
      - build_scipy
